name: Run tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture:   x64
      - name: Run tests
        run: |
          python -m venv test.env
          source test.env/bin/activate
          pip install -e .
          pytest
